version: '3'

volumes: 
  pihole:
  dnsmasq:

networks:
  pihole:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/16



# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  cloudflared:
    image: visibilityspots/cloudflared
    ports:
      - '5054:5054/tcp'
      - '5054:5054/udp'
    restart: unless-stopped
    networks:
      pihole:
        ipv4_address: 172.18.0.2
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '80:80/tcp'
      - '443:443/tcp'
    environment:
      TZ: 'Asia/Makassar'
      ServerIP: '192.168.2.50'
      WEBPASSWORD: 'set a secure'      
      DNS1: '172.18.0.2#5054'
      DNS2: 'no'
    volumes:
      - 'pihole:/etc/pihole/'
      - 'dnsmasq:/etc/dnsmasq.d/'
     # - './etc-pihole/:/etc/pihole/'
     # - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      pihole:
        ipv4_address: 172.18.0.3
